#!/bin/bash
/system/xbin/insmod /modules/dpram.ko
/system/xbin/insmod /modules/multipdp.ko
/system/xbin/chmod +rw /dev/*
/system/xbin/ln -s /sd/Phone_I8000XXJA1.bin /dev/bml9
/system/xbin/efsd &
/system/xbin/sleep 25
/system/xbin/ipctool 07 00 00 00 01 01 03                    # IPC_GSM_PWR_PHONE_PWR_UP NOTI
/system/xbin/sleep 5
/system/xbin/ipctool -d 07 00 02 ff 0a 01 02                 # IPC_GSM_MISC_ME_VERSION GET
/system/xbin/radiooptions 5
/system/xbin/sleep 5
/system/xbin/ipctool -d 07 00 02 ff 0a 01 02                 # IPC_GSM_MISC_ME_VERSION GET

> /tmp_log
STAT=1
while [ $STAT -gt 0 ]
do
    /system/xbin/ipctool 09 00 03 00 05 01 03 03 01        # IPC_GSM_SEC_PIN_STATUS NOTI
    /system/xbin/logcat -b radio > /tmp_log&
    /system/xbin/sleep 2
    /system/xbin/kill -9 $!
    /system/xbin/grep SIM_IO /tmp_log >/dev/null  2>&1
    STAT=$?
done
