#!/bin/bash
/sbin/insmod /modules/dpram.ko
/sbin/insmod /modules/multipdp.ko
/bin/chmod +rw /dev/*
/bin/ln -s /sd/Phone_I8000XXJA1.bin /dev/bml9
/system/bin/efsd &
/bin/sleep 25
/system/xbin/ipctool 07 00 00 00 01 01 03                    # IPC_GSM_PWR_PHONE_PWR_UP NOTI
/bin/sleep 5
/system/xbin/ipctool -d 07 00 02 ff 0a 01 02                 # IPC_GSM_MISC_ME_VERSION GET
/system/bin/radiooptions 5
/bin/sleep 5
/system/xbin/ipctool -d 07 00 02 ff 0a 01 02                 # IPC_GSM_MISC_ME_VERSION GET

> /tmp_log
STAT=1
while [ $STAT -gt 0 ]
do
    /system/xbin/ipctool 09 00 03 00 05 01 03 03 01        # IPC_GSM_SEC_PIN_STATUS NOTI
    /system/bin/logcat -b radio > /tmp_log&
    /bin/sleep 2
    /bin/kill -9 $!
    /bin/grep SIM_IO /tmp_log >/dev/null  2>&1
    STAT=$?
done
