##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: Throughc
##############################################################################
# VERSION&DATE	: Version 1.00	2007/12/25 (Throughc)
##############################################################################



obj-$(CONFIG_OPTICAL_GP2A)	+= gp2aP002S00F.o
obj-$(CONFIG_OPTICAL_ISL29023)	+= isl29023.o

